### PR TITLE
fix: resolved issue with being unable to scroll up in the input field

### LINKED ISSUE #455: [Bug]: Can not scroll up in messages windows.
### Hardware

Other

### Connection Type

HTTP

### Local or Hosted

https://client.meshtastic.org

### Firmware Version

864f807

### Description

Can not scroll up in messages window. Whatever messages are showing is what you get. Can not scroll up to see past messages. 

Image

### Relevant console output

```Shell

```

### PR DESCRIPTION
**Pull request by danditomaso**
## Description

This PR fixes an issue with the ChannelChat component that caused an issue when messaged scrolled off the top of the screen you couldn't scroll back to see them. 

## Related Issues

Fixes #455 

## Changes Made

- Moved MessageInput component the MessagesPage level that works for both chat types
- Fixed the layout structure to ensure proper scrolling behaviour
- Better handling of destination and channel props based on active chat type
- Fixed overflow issues for message history
- Added class which allows for hiding of scroll bar to improve UI appearance

## Testing Done

- Verified that messages can be sent to both direct message chats and broadcast channels 
- Confirmed that the message history scrolls properly and maintains position when new messages arrive
- Tested with multiple chat types to ensure the input always sends to the correct destination

## Checklist

- [X] Code follows project style guidelines
- [X] Tests have been added or updated
- [X] All CI checks pass
- [X] Dependent changes have been merged

### CODE REVIEW

File: src/components/PageComponents/Messages/MessageInput.tsx [hunk 1]
```diff
@@ -76,20 +80,24 @@ export const MessageInput = ({
     <div className="flex gap-2">
       <form
         className="w-full"
+        role="form"
```
Comment (bkimmel) [inline src/components/PageComponents/Messages/MessageInput.tsx]: Is this necessary? The `form` element already assumes the `form` role.

Comment (danditomaso) [reply src/components/PageComponents/Messages/MessageInput.tsx]: I can remove it.

Comment (danditomaso) [reply src/components/PageComponents/Messages/MessageInput.tsx]: I can remove it
